version: '3.8'

services:
  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
#    volumes:
#      - ./data/clickhouse:/var/lib/clickhouse

  backend:
    container_name: backend
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_DEBUG=1
      - MONGO_HOST=mongo
      - MONGO_DB=db
      - MONGO_COLLECTION=loft
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=123

  frontend:
    container_name: frontend
    build:
      context: frontend
    expose:
      - 3000
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules/
    stdin_open: true

  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123

  mongo-express:
    container_name: mongo_express
    image: mongo-express:1.0-20 # 0.54.0
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 123
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
      ME_CONFIG_MONGODB_URL: mongodb://root:123@mongo:27017/
